# Generated by Django 3.2.5 on 2021-07-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Razon Social')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('servicio', models.CharField(max_length=50, verbose_name='Servicio')),
            ],
        ),
    ]
