# Generated by Django 3.2.5 on 2021-07-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicio_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
